"""add user profile fields

Revision ID: 8b1d56d999b7
Revises: 
Create Date: 2026-03-24 19:54:17.013445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1d56d999b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_user_telegram_chat_id', ['telegram_chat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_telegram_chat_id', type_='unique')
        batch_op.drop_column('telegram_link_token')
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
